apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-deploy
spec:
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
     containers:
      - name: auth-api
        image: 0811198720119005/project-auth
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      
