apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-deploy
spec:
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        image: 0811198720119005/project-users
        env :
          - name: AUTH_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: auth-env
                key: AUTH_ADDRESS
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
